version: "3"
services:
  mongodb_container:
      container_name: database_mongodb
      image: mongo
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ~/.mongodb-data:/data/db
  api:
    container_name: api-clean-node-container
    image: node:18
    working_dir: /user/src/app
    command: bash -c "npm install --only=prod && npm run start"
    volumes:
      - ./dist/:/user/src/app/dist/
      - ./package.json:/user/src/app/package.json
    ports:
      - 5050:5050
      - 9222:9222

    links:
      - mongodb_container