version: '3.4'

services:
  cleannodeapitdd:
    image: cleannodeapitdd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9222:9222
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
