version: 2.1
  jobs:
    test:
      steps:
        - checkout
        - run: echo "Running tests"
        - run: npm install
        - run: npx eslint 'src/**' 
        - run: npm run test:coveralls

workflows:
  version: 2.1
    test_build:
      jobs:
        - test
        