version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
    jobs:
      - node/test:
          version: '18.12'
          pkg-manager: yarn

          run:
            command: eslint 'src/**' && yarn test:coveralls